### ISSUE TITLE
Remote debugging on a Raspberry Pi

### ISSUE THREAD

**Issue by Thorinos** [Kode/vscode-electron-debug#3]
Hello, this is my setup:

**Host**: Linux Ubuntu 19.06 64 bits
Visual Studio Code - Insiders 1.38.0
Extensions installed: Debugger for Electron 18.11.1, Remote-SSH, Debugger for Chrome

**Remote**: Raspbian Buster With desktop 2019-07-10
Remote extensions installed: Debugger for Electron 18.11.1

I am able to connect to the remote via SSH with VS Code Insiders to the Raspberry Pi. My Electron app is the [Electron Quick Start sample](https://github.com/electron/electron-quick-start). 

This is the launch.json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "electron",
            "request": "launch",
            "name": "Launch Electron",
            "sourceMaps": true,
            "trace": "verbose",
            "appDir": "${workspaceFolder}",
            "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron"
        }
    ],
}
```
I did try this same configuration on a Linux machine. Locally, it is working just fine. I can set breakpoint inside JS code and all it's good. But I'm facing issue while remote debugging on another machine.

And I'm getting the message below while trying to start debugging (this is the end of the log, I can send you all the log if you want to have more information): 
```
Discovering targets via http://127.0.0.1:14400/json
HTTP GET failed: Error: connect ECONNREFUSED 127.0.0.1:14400
To client: {"seq":0,"type":"event","event":"output","body":{"category":"telemetry","output":"ClientRequest/launch","data":{"Versions.DebugAdapterCore":"6.7.31","Versions.DebugAdapter":"18.11.1","successful":"false","exceptionType":"firstChance","exceptionMessage":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","exceptionName":"Error","exceptionStack":"Error: Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).\n    at Object.runtimeConnectionTimeout (/home/pi/.vscode-server-insiders/extensions/kodetech.electron-debug-18.11.1/node_modules/vscode-chrome-debug-core/out/src/errors.js:91:12)\n    at utils.retryAsync.catch.err (/home/pi/.vscode-server-insiders/extensions/kodetech.electron-debug-18.11.1/node_modules/vscode-chrome-debug-core/out/src/chrome/chromeConnection.js:110:49)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","exceptionId":"2010","timeTakenInMilliseconds":"10003.520802","requestType":"request"}}}
To client: {"seq":0,"type":"response","request_seq":2,"command":"launch","success":false,"message":"Cannot connect to runtime process, timeout after 10000 ms - (reason: Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:14400).","body":{"error":{"id":2010,"format":"Cannot connect to runtime process, timeout after {_timeout} ms - (reason: {_error}).","variables":{"_error":"Cannot connect to the target: connect ECONNREFUSED 127.0.0.1:14400","_timeout":"10000"}}}}

```
I'm stuck there and I would really like to be able to remote debugging an Electron app on a ARM64 from VSCode on another computer. Do someone have suggestions on how to fix this?

**Comment by RobDangerous** [comment]
Not really but try to use a pwa-chrome launch config instead of this extension.
